### ISSUE TITLE
The XMR view key can suddenly become invalid

### ISSUE THREAD

**Issue by nanostos** [bitrequest/bitrequest.github.io#13]
For context, integrated addresses were active when this error occurred. View key was added with address setup. Using web app, with defaults.

Steps:
1. Produce request and pay amount, which is detected correctly and then stored under Requests. 
2. When opening new request window, error pops up "Error: Invalid Viewkey". 
3. Payment of this second request is now NOT detected.

No change was made to the wallet. I also cannot see any way to look at or change the view key associated with an address after it has been added the first time.

**Comment by bitrequest** [comment]
I haven't been able to reproduce this, but i do found the error message might be incorrect. It showed when there was a connection error in general not necessarily related to the viewkey: https://github.com/bitrequest/bitrequest.github.io/commit/ceaa4c8d77681f97a50512056f8b797524948255

The viewkey should always be correct, since there's a check when entering it into the app.
If you do wanna change it you can delete the address and reenter your address and viewkey.
