### ISSUE TITLE
Feature request: Move the transaction description field to the front of the request window, where the amount field is

### ISSUE THREAD

**Issue by nanostos** [bitrequest/bitrequest.github.io#14]
This is in the context of using Bitrequest for an XMR physical point of sale solution.

Even better if the description is also then encoded in the QR code so that the sender's wallet picks it up. Flipping back and forth to edit this for every txn is not ideal when trying to quickly serve customers.

**Comment by bitrequest** [comment]
I have cosidered this, but since it takes up a lot of space and is not always used i decided to keep it on the back.
For merchants you would need to ad a little routine to flip the request and enter the description. Because of this inconvenience i added also the possibility to add a description afterwards in the request overview.

I am not sure yet to encode the description in the URI / QR, since it might be a problem with large descriptions. And i don't think a lot of wallets support this feature. (Not sure)

**Comment by nanostos** [comment]
I know this is just one datapoint, so it might not be very persuasive, but I find the flipping a bit cumbersome. What about simply making the window longer, so you can scroll down to add the description? I'm imagining the QR code to remain static when scrolling so that it remains on screen and you don't have to scroll back up to bring it into view again.

As for description in the URI, that's more a 'nice to have'. I know that the popular Cake Wallet supports it but Monerujo doesn't. But I've been meaning to contact the Monerujo devs about it anyway, since the standard desktop wallets do support adding the description to the URI for QR display. With regards to length, maybe you could just have a cutoff, so that only the first e.g. 20 characters are encoded? Customer won't need a long description but it is nice for them to see the wallet automatically grab the txn description for future record (the way your banking app automatically shows where your outgoing txns all went).

**Comment by bitrequest** [comment]
Again, im a sucker for keeping things lean and clean so im for leaving out the description field for POS. For sharing it's essential. Adding the description to the URI will be on my todo list. Have to see how it effects performance an the QR code.

Maybe for now the merchant can add a description afterwards in the request overview. Also considering XMR payments will not occur very frequently until mass adoption ;-)
